### ISSUE TITLE
Umbrella project has `nil` application and other symptoms

### ISSUE THREAD

**Issue by seancribbs** [gabrielgatu/mix-dialyzer#2]
I can't build/copy a PLT in my umbrella project, it fails on this error:

```shell
$ mix dialyzer
* - Dialyzer: configuration file not found. Creating it right now at .dialyzer.exs
* - Creating one or more missing plt.
* - Copying dialyzer_erlang-20-erts-9.3.3_elixir-1.6.5.plt to dialyzer_erlang-20-erts-9.3.3_elixir-1.6.5_deps.plt
** (UndefinedFunctionError) function nil.mods/0 is undefined or private
    nil.mods()
    (mix_dialyzer) lib/dialyzer/plt/builder.ex:86: anonymous fn/1 in Dialyzer.Plt.Builder.collect_files_from_apps/1
    (elixir) lib/enum.ex:2924: Enum.flat_map_list/2
    (elixir) lib/enum.ex:2925: Enum.flat_map_list/2
    (mix_dialyzer) lib/dialyzer/plt/builder.ex:86: Dialyzer.Plt.Builder.collect_files_from_apps/1
    (mix_dialyzer) lib/dialyzer/plt/builder.ex:73: Dialyzer.Plt.Builder.build_plt/3
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
```

Here's the output of `mix dialyzer.info`, note the "invisible" application, the `nil` app name, and the contained app `ordering_models` that is in the "Project applications" section (a sibling app depends on it):

```shell
$ mix dialyzer.info

Welcome to mix dialyzer! A tool for integrating dialyzer into a project and analyzing discrepances.
Here are some infos about your system:

## Application name

nil

## Applications included into analysis


  ### Erlang applications

  * erts
  * kernel
  * stdlib
  * crypto

  ### Elixir applications

  * elixir

  ### Project applications

  * asn1
  * compiler
  * connection
  * cowboy
  * cowlib
  * crypto
  * db_connection
  * decimal
  * ecto
  * eex
  * file_system
  * gettext
  * kernel
  * logger
  * mime
  * ordering_models
  * phoenix
  * phoenix_ecto
  * phoenix_html
  * phoenix_live_reload
  * phoenix_pubsub
  * plug
  * poison
  * poolboy
  * postgrex
  * public_key
  * ranch
  * runtime_tools
  * ssl
  * stdlib
  *
  * erts
  * kernel
  * stdlib
  * crypto
  * elixir
```

**Comment by gabrielgatu** [comment]
Thanks! ❤️ Resolved by: 6aba106
